### ISSUE TITLE
Poorly formed patch transform causes nil ref and crash loop in crossplane

### ISSUE THREAD

**Issue by jbw976** [crossplane/crossplane#1815]
### What happened?

I authored a poorly formed patch transform, which resulted in a nil ref and a crash loop of the crossplane pod. Ideally, invalid compositions should not result in crashes, they should be handled more gracefully with a helpful error message.

```yaml
      patches:
      - fromFieldPath: "metadata.uid"
        toFieldPath: "spec.writeConnectionSecretToRef.name"
        transforms:
          - type: string
            fmt: "%s-postgresql"
```

The transform is invalid because it's specifying the `type: string` as a map when it should be just a field.

This resulted in the following relevant error message and stack trace:

```
E1008 03:32:08.384765       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 659 [running]:
...
	/usr/local/go/src/runtime/panic.go:969 +0x166
github.com/crossplane/crossplane/apis/apiextensions/v1alpha1.(*StringTransform).Resolve(0x0, 0x171b4c0, 0xc0013afeb0, 0xc001497090, 0xc000988ac0, 0x2, 0x2)
	/Users/jared/dev/go/src/github.com/crossplane/crossplane/apis/apiextensions/v1alpha1/composition_types.go:317 +0x42
github.com/crossplane/crossplane/apis/apiextensions/v1alpha1.(*Transform).Transform(0xc001497098, 0x171b4c0, 0xc0013afeb0, 0x0, 0x0, 0x0, 0x0)
	/Users/jared/dev/go/src/github.com/crossplane/crossplane/apis/apiextensions/v1alpha1/composition_types.go:241 +0x15c
github.com/crossplane/crossplane/apis/apiextensions/v1alpha1.(*Patch).Apply(0xc001497188, 0x7f8b625a24c0, 0xc00048a6d0, 0x7f8b62627458, 0xc00009aab8, 0x1, 0x19a2020)
	/Users/jared/dev/go/src/github.com/crossplane/crossplane/apis/apiextensions/v1alpha1/composition_types.go:172 +0x1ea
github.com/crossplane/crossplane/pkg/controller/apiextensions/composite/composed.(*DefaultOverlayApplicator).Overlay(0x2a60028, 0x1d8b1a0, 0xc00048a6d0, 0x1d85d00, 0xc00009aab8, 0xc0015f8540, 0x1af, 0x1af, 0x0, 0x0, ...)
	/Users/jared/dev/go/src/github.com/crossplane/crossplane/pkg/controller/apiextensions/composite/composed/api.go:107 +0x169
github.com/crossplane/crossplane/pkg/controller/apiextensions/composite/composed.(*Composer).Compose(0xc000822ba0, 0x1d547a0, 0xc000eff1a0, 0x1d8b1a0, 0xc00048a6d0, 0x1d85d00, 0xc00009aab8, 0xc0015f8540, 0x1af, 0x1af, ...)
	/Users/jared/dev/go/src/github.com/crossplane/crossplane/pkg/controller/apiextensions/composite/composed/composed.go:166 +0x145
github.com/crossplane/crossplane/pkg/controller/apiextensions/composite.(*Reconciler).Reconcile(0xc0001f3480, 0x0, 0x0, 0xc000dc39a0, 0xb, 0xc00139d800, 0x0, 0x0, 0x0)
	/Users/jared/dev/go/src/github.com/crossplane/crossplane/pkg/controller/apiextensions/composite/reconciler.go:274 +0x16b0
```

### How can we reproduce it?

Create a composition with a transform like above, then create an instance that will use that composition.

### What environment did it happen in?
Crossplane version: `v0.13.0-rc.326.g41076fca`

**Comment by muvaf** [comment]
This should have been taken care of by https://github.com/crossplane/crossplane/blob/19fc561/apis/apiextensions/v1alpha1/composition_types.go#L238

I'm debugging it via IDE right now and `transformer == nil` doesn't return `true` even though IDE says it's `nil`. It might have to do with `transformer` being a `func` type. Digging.

**Comment by muvaf** [comment]
Hmm, [that](https://play.golang.org/p/pVE0l5b1neK)'s weird. I guess there is something I don't know about Go `nil`s.
