### ISSUE TITLE
Panic when running Crossplane with `--enable-composition-revisions`

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#2825]
### What happened?

Crossplane crashes when the alpha Composition Revisions feature is enabled:

```
$ go run cmd/crossplane/main.go core start --enable-composition-revisions
I0106 21:32:25.270423  132932 request.go:668] Waited for 1.039107689s due to client-side throttling, not priority and fairness, request: GET:https://127.0.0.1:33451/apis/node.k8s.io/v1beta1?timeout=32s
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x145c527]

goroutine 1 [running]:
github.com/alecthomas/kong.catch(0xc000757e48)
        /home/negz/control/go/pkg/mod/github.com/alecthomas/kong@v0.2.17/kong.go:398 +0xa5
panic({0x18a4000, 0x2b72300})
        /usr/lib/go-1.17/src/runtime/panic.go:1038 +0x215
github.com/crossplane/crossplane-runtime/pkg/feature.(*Flags).Enable(0x0, {0x1aed797, 0x1f})
        /home/negz/control/go/pkg/mod/github.com/crossplane/crossplane-runtime@v0.15.1-0.20211029211307-c72bcdd922eb/pkg/feature/feature.go:35 +0x27
github.com/crossplane/crossplane/cmd/crossplane/core.(*startCommand).Run(0x2b95c48, 0xc00047c9a0, {0x1da06d8, 0xc000117b20})
        /home/negz/control/crossplaneio/crossplane/cmd/crossplane/core/core.go:110 +0x44f
reflect.Value.call({0x186cd80, 0x2b95c48, 0x30}, {0x1acc057, 0x4}, {0xc0005192f0, 0x2, 0x18})
        /usr/lib/go-1.17/src/reflect/value.go:543 +0x814
reflect.Value.Call({0x186cd80, 0x2b95c48, 0x5}, {0xc0005192f0, 0x2, 0x2})
        /usr/lib/go-1.17/src/reflect/value.go:339 +0xc5
github.com/alecthomas/kong.callMethod({0x1acbbf0, 0x3}, {0x1a07480, 0x2b95c48, 0x3}, {0x186cd80, 0x2b95c48, 0xc0005c9d88}, 0x13b74e5)
        /home/negz/control/go/pkg/mod/github.com/alecthomas/kong@v0.2.17/callbacks.go:71 +0x4e7
github.com/alecthomas/kong.(*Context).RunNode(0xc0005a4a00, 0xc00039e1c0, {0xc0005c9ef0, 0x1, 0x1})
        /home/negz/control/go/pkg/mod/github.com/alecthomas/kong@v0.2.17/context.go:715 +0x40b
github.com/alecthomas/kong.(*Context).Run(0x1789dc0, {0xc0005c9ef0, 0x1, 0x1})
        /home/negz/control/go/pkg/mod/github.com/alecthomas/kong@v0.2.17/context.go:732 +0xa5
main.main()
        /home/negz/control/crossplaneio/crossplane/cmd/crossplane/main.go:89 +0x4e5
exit status 2
```

### How can we reproduce it?

See above

### What environment did it happen in?
Crossplane version: v1.6.0

**Comment by kertzi** [comment]
Hello, 
I'm hitting this with crossplane version 1.8.1 also, at least when running in minikube
Logs from crashing crossplane pod

```
I0629 05:15:05.566995       1 request.go:665] Waited for 1.047309675s due to client-side throttling, not priority and fairness, request: GET:https://10.96.0.1:443/apis/pkg.crossplane.io/v1?timeout=32s
{"level":"info","ts":1656479709.9150047,"logger":"crossplane","msg":"Alpha feature enabled","flag":"EnableAlphaCompositionRevisions"}
I0629 05:15:10.014694       1 leaderelection.go:248] attempting to acquire leader lease crossplane-system/crossplane-leader-election-core...
I0629 05:16:13.884607       1 leaderelection.go:258] successfully acquired lease crossplane-system/crossplane-leader-election-core
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x155f1f3]

goroutine 666 [running]:
github.com/crossplane/crossplane/internal/controller/apiextensions/composition.NewCompositionRevisionTransform(...)
	/home/runner/work/crossplane/crossplane/internal/controller/apiextensions/composition/revision.go:164
github.com/crossplane/crossplane/internal/controller/apiextensions/composition.NewCompositionRevisionPatch({{0xc00016f908, 0x14}, 0xc00130efe0, 0x0, 0xc00130eff0, 0x0, {0xc001314900, 0x1, 0x1}, 0x0})
	/home/runner/work/crossplane/crossplane/internal/controller/apiextensions/composition/revision.go:142 +0x413
github.com/crossplane/crossplane/internal/controller/apiextensions/composition.NewCompositionRevisionComposedTemplate({0xc00130eea0, {{0xc00132e200, 0xfc, 0xfc}, {0x0, 0x0}}, {0xc000101000, 0xc, 0xc}, {0xc000842580, ...}, ...})
	/home/runner/work/crossplane/crossplane/internal/controller/apiextensions/composition/revision.go:101 +0x258
github.com/crossplane/crossplane/internal/controller/apiextensions/composition.NewCompositionRevisionSpec({{{0xc0007522e0, 0x1d}, {0xc00016eac8, 0x12}}, {0xc0002c8a00, 0x4, 0x4}, {0xc001336000, 0x24, 0x24}, ...}, ...)
	/home/runner/work/crossplane/crossplane/internal/controller/apiextensions/composition/revision.go:69 +0x3e5
github.com/crossplane/crossplane/internal/controller/apiextensions/composition.NewCompositionRevision(0xc00131e300, 0x209bec8, {0xc002766440, 0x10})
	/home/runner/work/crossplane/crossplane/internal/controller/apiextensions/composition/revision.go:38 +0x187
github.com/crossplane/crossplane/internal/controller/apiextensions/composition.(*Reconciler).Reconcile(0xc0009a1d40, {0x209bf00, 0xc001314300}, {{{0x0, 0xc000abdc30}, {0xc0000529c0, 0x30}}})
	/home/runner/work/crossplane/crossplane/internal/controller/apiextensions/composition/reconciler.go:196 +0x14c5
github.com/crossplane/crossplane-runtime/pkg/ratelimiter.(*Reconciler).Reconcile(0xc000181400, {0x209bf00, 0xc001314300}, {{{0x0, 0x1ce80a0}, {0xc0000529c0, 0x30}}})
	/home/runner/work/crossplane/crossplane/vendor/github.com/crossplane/crossplane-runtime/pkg/ratelimiter/reconciler.go:54 +0x16b
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0xc00023c000, {0x209bf00, 0xc0013142d0}, {{{0x0, 0x1ce80a0}, {0xc0000529c0, 0x413ab4}}})
	/home/runner/work/crossplane/crossplane/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:114 +0x26f
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00023c000, {0x209be58, 0xc000828340}, {0x1bd53e0, 0xc000732120})
	/home/runner/work/crossplane/crossplane/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:311 +0x33e
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00023c000, {0x209be58, 0xc000828340})
	/home/runner/work/crossplane/crossplane/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:266 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/home/runner/work/crossplane/crossplane/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:227 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/home/runner/work/crossplane/crossplane/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:223 +0x357
```

**Comment by jbw976** [comment]
Re-opening to investigate into this potential regression, thank you for reporting this @kertzi 🙇

**Comment by negz** [comment]
This isn't the same issue / a regression. If you read the stack traces you'll see they're in two different parts of the codebase. The two issues just both happen to relate to Composition Revisions and both happen to cause panics. I think this is related to https://github.com/crossplane/crossplane/issues/3113 so let's track it there.
