### ISSUE TITLE
Partial composition revision propagation

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#3113]
### What happened?

We have code in `internal/controller/apiextensions/composition/revision.go` that syncs a Composition with a Composition Revision. I believe we've extended the Composition API type a few times but forgot to update this file to propagate the code. We need to audit it to ensure everything is being copied across.

**Comment by jwjs36987** [comment]
As part of fixing this would it be possible for crossplane to log an error if they are out of sync/it hits something it doesn't recognize? It took quite a while to work out what was happening (see #3130)

**Comment by negz** [comment]
@jwjs36987 I'd rather detect this at build time than runtime - it should be possible to detect the schemas being out of sync.

**Comment by negz** [comment]
Another report from @kertzi in https://github.com/crossplane/crossplane/issues/2825#issuecomment-1169549620:

```
I0629 05:15:05.566995       1 request.go:665] Waited for 1.047309675s due to client-side throttling, not priority and fairness, request: GET:https://10.96.0.1:443/apis/pkg.crossplane.io/v1?timeout=32s
{"level":"info","ts":1656479709.9150047,"logger":"crossplane","msg":"Alpha feature enabled","flag":"EnableAlphaCompositionRevisions"}
I0629 05:15:10.014694       1 leaderelection.go:248] attempting to acquire leader lease crossplane-system/crossplane-leader-election-core...
I0629 05:16:13.884607       1 leaderelection.go:258] successfully acquired lease crossplane-system/crossplane-leader-election-core
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x155f1f3]

goroutine 666 [running]:
github.com/crossplane/crossplane/internal/controller/apiextensions/composition.NewCompositionRevisionTransform(...)
	/home/runner/work/crossplane/crossplane/internal/controller/apiextensions/composition/revision.go:164
github.com/crossplane/crossplane/internal/controller/apiextensions/composition.NewCompositionRevisionPatch({{0xc00016f908, 0x14}, 0xc00130efe0, 0x0, 0xc00130eff0, 0x0, {0xc001314900, 0x1, 0x1}, 0x0})
	/home/runner/work/crossplane/crossplane/internal/controller/apiextensions/composition/revision.go:142 +0x413
github.com/crossplane/crossplane/internal/controller/apiextensions/composition.NewCompositionRevisionComposedTemplate({0xc00130eea0, {{0xc00132e200, 0xfc, 0xfc}, {0x0, 0x0}}, {0xc000101000, 0xc, 0xc}, {0xc000842580, ...}, ...})
	/home/runner/work/crossplane/crossplane/internal/controller/apiextensions/composition/revision.go:101 +0x258
github.com/crossplane/crossplane/internal/controller/apiextensions/composition.NewCompositionRevisionSpec({{{0xc0007522e0, 0x1d}, {0xc00016eac8, 0x12}}, {0xc0002c8a00, 0x4, 0x4}, {0xc001336000, 0x24, 0x24}, ...}, ...)
	/home/runner/work/crossplane/crossplane/internal/controller/apiextensions/composition/revision.go:69 +0x3e5
github.com/crossplane/crossplane/internal/controller/apiextensions/composition.NewCompositionRevision(0xc00131e300, 0x209bec8, {0xc002766440, 0x10})
	/home/runner/work/crossplane/crossplane/internal/controller/apiextensions/composition/revision.go:38 +0x187
github.com/crossplane/crossplane/internal/controller/apiextensions/composition.(*Reconciler).Reconcile(0xc0009a1d40, {0x209bf00, 0xc001314300}, {{{0x0, 0xc000abdc30}, {0xc0000529c0, 0x30}}})
	/home/runner/work/crossplane/crossplane/internal/controller/apiextensions/composition/reconciler.go:196 +0x14c5
github.com/crossplane/crossplane-runtime/pkg/ratelimiter.(*Reconciler).Reconcile(0xc000181400, {0x209bf00, 0xc001314300}, {{{0x0, 0x1ce80a0}, {0xc0000529c0, 0x30}}})
	/home/runner/work/crossplane/crossplane/vendor/github.com/crossplane/crossplane-runtime/pkg/ratelimiter/reconciler.go:54 +0x16b
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0xc00023c000, {0x209bf00, 0xc0013142d0}, {{{0x0, 0x1ce80a0}, {0xc0000529c0, 0x413ab4}}})
	/home/runner/work/crossplane/crossplane/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:114 +0x26f
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00023c000, {0x209be58, 0xc000828340}, {0x1bd53e0, 0xc000732120})
	/home/runner/work/crossplane/crossplane/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:311 +0x33e
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00023c000, {0x209be58, 0xc000828340})
	/home/runner/work/crossplane/crossplane/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:266 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/home/runner/work/crossplane/crossplane/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:227 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/home/runner/work/crossplane/crossplane/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:223 +0x357
```

**Comment by negz** [comment]
I'm working on back porting this fix to 1.8, 1.7, and 1.6.
