### ISSUE TITLE
Crossplane init Error

### ISSUE THREAD

**Issue by iKubernetes** [crossplane/crossplane#4272]
### What happened?

When I install crossplane (v1.12.2) with helm, the crossplane and crossplane-rbac-manager pod returns "init Error". The logs of init container in crossplane pod:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x13fccf0]

goroutine 1 [running]:
k8s.io/client-go/discovery.convertAPIResource(...)
        k8s.io/client-go@v0.26.3/discovery/aggregated_discovery.go:114
k8s.io/client-go/discovery.convertAPIGroup({{{0x0, 0x0}, {0x0, 0x0}}, {{0xc000164120, 0x15}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...})
        k8s.io/client-go@v0.26.3/discovery/aggregated_discovery.go:95 +0x6f0
k8s.io/client-go/discovery.SplitGroupsAndResources({{{0xc000059908, 0x15}, {0xc000206d80, 0x1b}}, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...})
        k8s.io/client-go@v0.26.3/discovery/aggregated_discovery.go:49 +0x125
k8s.io/client-go/discovery.(*DiscoveryClient).downloadAPIs(0xc0004b8988?)
        k8s.io/client-go@v0.26.3/discovery/discovery_client.go:328 +0x3de
k8s.io/client-go/discovery.(*DiscoveryClient).GroupsAndMaybeResources(0xc0004b8db8?)
        k8s.io/client-go@v0.26.3/discovery/discovery_client.go:203 +0x65
k8s.io/client-go/discovery.ServerGroupsAndResources({0x2484ca8, 0xc0002c5e00})
        k8s.io/client-go@v0.26.3/discovery/discovery_client.go:413 +0x59
k8s.io/client-go/discovery.(*DiscoveryClient).ServerGroupsAndResources.func1()
        k8s.io/client-go@v0.26.3/discovery/discovery_client.go:376 +0x25
k8s.io/client-go/discovery.withRetries(0x2, 0xc000592dd0)
        k8s.io/client-go@v0.26.3/discovery/discovery_client.go:651 +0x71
k8s.io/client-go/discovery.(*DiscoveryClient).ServerGroupsAndResources(0x0?)
        k8s.io/client-go@v0.26.3/discovery/discovery_client.go:375 +0x3a
k8s.io/client-go/restmapper.GetAPIGroupResources({0x2484ca8?, 0xc0002c5e00?})
        k8s.io/client-go@v0.26.3/restmapper/discovery.go:148 +0x42
sigs.k8s.io/controller-runtime/pkg/client/apiutil.NewDynamicRESTMapper.func1()
        sigs.k8s.io/controller-runtime@v0.14.6/pkg/client/apiutil/dynamicrestmapper.go:94 +0x25
sigs.k8s.io/controller-runtime/pkg/client/apiutil.(*dynamicRESTMapper).setStaticMapper(...)
        sigs.k8s.io/controller-runtime@v0.14.6/pkg/client/apiutil/dynamicrestmapper.go:130
sigs.k8s.io/controller-runtime/pkg/client/apiutil.NewDynamicRESTMapper(0xc000202900?, {0x0, 0x0, 0x216d850?})
        sigs.k8s.io/controller-runtime@v0.14.6/pkg/client/apiutil/dynamicrestmapper.go:110 +0x182
sigs.k8s.io/controller-runtime/pkg/client.newClient(0xc000202900?, {0xc0003ff730?, {0x0?, 0x0?}, {0xc0?, 0xca?}})
        sigs.k8s.io/controller-runtime@v0.14.6/pkg/client/client.go:109 +0x1d1
sigs.k8s.io/controller-runtime/pkg/client.New(...)
        sigs.k8s.io/controller-runtime@v0.14.6/pkg/client/client.go:77
github.com/crossplane/crossplane/cmd/crossplane/core.(*initCommand).Run(0x344f300, 0xc0001ef898?, {0x247a360, 0xc000445548})
        github.com/crossplane/crossplane/cmd/crossplane/core/init.go:55 +0x11f
reflect.Value.call({0x1e219c0?, 0x344f300?, 0x451356?}, {0x2154f53, 0x4}, {0xc0002c57a0, 0x2, 0x2?})
        reflect/value.go:586 +0xb0b
reflect.Value.Call({0x1e219c0?, 0x344f300?, 0x1e9ff40?}, {0xc0002c57a0?, 0x2150960?, 0xc0004b9b88?})
        reflect/value.go:370 +0xbc
github.com/alecthomas/kong.callFunction({0x1e219c0?, 0x344f300?, 0x56a73c?}, 0x1?)
        github.com/alecthomas/kong@v0.7.2-0.20221130112736-919e70103f7a/callbacks.go:98 +0x445
github.com/alecthomas/kong.callMethod({0x21549dd, 0x3}, {0x2061e80?, 0x344f300?, 0x3?}, {0x1e219c0?, 0x344f300?, 0x2170825?}, 0x15?)
        github.com/alecthomas/kong@v0.7.2-0.20221130112736-919e70103f7a/callbacks.go:132 +0x76
github.com/alecthomas/kong.(*Context).RunNode(0xc0000ba400, 0xc0003f0780, {0xc0004b9ee8, 0x1, 0x1})
        github.com/alecthomas/kong@v0.7.2-0.20221130112736-919e70103f7a/context.go:762 +0x60f
github.com/alecthomas/kong.(*Context).Run(0x1d022a0?, {0xc0004b9ee8?, 0x0?, 0xc0004b9ee8?})
        github.com/alecthomas/kong@v0.7.2-0.20221130112736-919e70103f7a/context.go:787 +0x14e
main.main()
        github.com/crossplane/crossplane/cmd/crossplane/main.go:105 +0x5af
``` 

### What environment did it happen in?
Crossplane version:  v1.12.2

#### Cloud provider or hardware configuration
Kubernetes version (use `kubectl version`): v1.27.3
Kubernetes distribution (e.g. Tectonic, GKE, OpenShift): kubeadm
OS (e.g. from /etc/os-release): Ubuntu Server 22.04
Kernel (e.g. `uname -a`): 5.15.0-75-generic

**Comment by negz** [comment]
@iKubernetes Is this easy to reproduce? If so, can you let us know how?

**Comment by jbw976** [comment]
I wasn't able to reproduce simply by installing latest helm chart (v1.12.2) using the [docs instructions](https://docs.crossplane.io/v1.12/software/install/) in a local kind cluster.  Anything else about the environment here that could be relevant? 🤔 

```
❯ kubectl -n crossplane-system get pod
NAME                                       READY   STATUS    RESTARTS   AGE
crossplane-65867555f7-xwtmk                1/1     Running   0          5m28s
crossplane-rbac-manager-57f7949747-ttcqg   1/1     Running   0          5m28s

❯ kubectl -n crossplane-system get pod -o json | jq '.items[].spec.containers[].image'
"crossplane/crossplane:v1.12.2"
"crossplane/crossplane:v1.12.2"
```

**Comment by iKubernetes** [comment]
My Kubernetes （v1.27.3）cluster was initialized by kubeadm init and runs on several KVM virtual machines. I was using the helm command to install it according to the instructions in the crossplane document on this Kubernetes cluster, and then I got this error message. There are no more special settings.

**Comment by ezgidemirel** [comment]
Hi @iKubernetes , we believe the older client-go version is causing this problem. Please check the [issue](https://github.com/upbound/universal-crossplane/issues/385) for further details. 

We bumped the version on master, but it's not released yet. Can you try the RC version if you're not using the Crossplane on prod?

**Comment by iKubernetes** [comment]
Yes, I am running crossplane in a non-production environment. I’ll try the RC version. Thank you for your reply.

> Hi @iKubernetes , we believe the older client-go version is causing this problem. Please check the [issue](https://github.com/upbound/universal-crossplane/issues/385) for further details.
> 
> We bumped the version on master, but it's not released yet. Can you try the RC version if you're not using the Crossplane on prod?

**Comment by turkenh** [comment]
Crossplane [v1.13.0](https://github.com/crossplane/crossplane/releases/tag/v1.13.0) is coming soon, and I assume the issue is fixed there.

I will close this issue as fixed but feel free to reopen it if it still happens.
